import "./globals.css";

export const metadata = {
  title: "Realtime Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Share+Tech&display=swap"
          rel="stylesheet"
        />
    
      </head>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
